//package 
//as we did not run the file from a specif folder, package is left as a comment.

import java.util.Scanner;

/**
 * In this project, we have generated the required Main java file to play a game of hangman with the addition of new Hangman class and methods within it which will be generated by other groups
 *This is the main class of the "Hangman" game.
 *
 * @author Pelin Öner, Yiğit İlk, Yusuf Kesmen
 * @date 08.2.2022
 */
public class Hangman_main
{
    static  Scanner in = new Scanner(System.in); //initializing the scanner for inputs
    public static void main(String[] args)
    {
        System.out.println("Welcome to the Hangman Game. Try to guess the secret word!");
        System.out.println();

        Hangman hangmanInMain = new Hangman();//The Hangman object used in our main class

        //This checks if number of incorrect attempts are not over maximum and the game is not over and takes letter input from user
        while( hangmanInMain.getNumOfIncorrectTries() <= hangmanInMain.getMaxAllowedIncorrectTries() && ! hangmanInMain.isGameOver())
            {
                //Displays the word and all letters available
                System.out.println( "Here is the word to guess : " + hangmanInMain.getKnownSoFar() );
                System.out.println( "Here is the letter list to be used : " + hangmanInMain.getAllLetters() );


                System.out.print( "Please enter a letter to guess the word: " );
                char letter = in.next().charAt(0); //Char may also be used depending on the methods in Hangman class

               //This checks whether the entered letter is used or not
                if ( hangmanInMain.getUsedLetters().indexOf(String.valueOf(letter)) != -1)
                {
                    System.out.println( "This is already used. Try another one!" );
                }

                //This checks if letter entered by user is in English alphabet   (available to use)
                else if ( hangmanInMain.getAllLetters().indexOf(String.valueOf(letter)) == -1)
                {
                    System.out.println( "This is not a letter to be used!" );
                }

                else
                {
                    int triedLetterCount = hangmanInMain.tryThis(letter);
                    
                    if ( triedLetterCount  > 0)
                    {
                        System.out.println( "Number of the occurances of the letter is " + triedLetterCount  );
                    }
                    
                    else
                    {
                        image(hangmanInMain.getNumOfIncorrectTries() );
                    }
                    System.out.println( "You have " + (hangmanInMain.getMaxAllowedIncorrectTries() - hangmanInMain.getNumOfIncorrectTries()) + " tries left! ");
                }
                System.out.println();

            }

        if ( hangmanInMain.hasLost())
            System.out.println( "You lose the game!" );
            //We were unsure whether the getKnownSoFar() method provided us with the unrevealed word even when the game was lost so we wanted to leave it as a comment:
            //System.out.println("The word was: " + hangmanInMain.getKnownSoFar());
        else if (hangmanInMain.getKnownSoFar().toString().equals(hangmanInMain.getSecretWord().toString()))
        {
            System.out.println( "You win the game!" );
            System.out.println( "The word is: " + hangmanInMain.getKnownSoFar());
        }

        System.out.println();
    }

    public static void image ( int count )// Was modified and taken from: https://gist.github.com/SedaKunda/79e1d9ddc798aec3a366919f0c14a078
    //As the images cannot be changed when the maxAllowedIncorrectTries change, we decided to leave it with "6" chances which was stated in the slides
    {
        if (count == 1) {
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("___|___");
        }
        if (count == 2) {
            System.out.println("   ____________");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   | ");
            System.out.println("___|___");
        }
        if (count == 3) {
            System.out.println("   ____________");
            System.out.println("   |          _|_");
            System.out.println("   |         /   \\");
            System.out.println("   |        |     |");
            System.out.println("   |         \\_ _/");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("   |");
            System.out.println("___|___");
        }
        if (count == 4) {
            System.out.println("   ____________");
            System.out.println("   |          _|_");
            System.out.println("   |         /   \\");
            System.out.println("   |        |     |");
            System.out.println("   |         \\_ _/");
            System.out.println("   |           |");
            System.out.println("   |           |");
            System.out.println("   |");
            System.out.println("___|___");
        }
        if (count == 5) {
            System.out.println("   ____________");
            System.out.println("   |          _|_");
            System.out.println("   |         /   \\");
            System.out.println("   |        |     |");
            System.out.println("   |         \\_ _/");
            System.out.println("   |           |");
            System.out.println("   |           |");
            System.out.println("   |          / \\ ");
            System.out.println("___|___      /   \\");
        }
        if (count == 6) {
            System.out.println("   ____________");
            System.out.println("   |          _|_");
            System.out.println("   |         /   \\");
            System.out.println("   |        |     |");
            System.out.println("   |         \\_ _/");
            System.out.println("   |          _|_");
            System.out.println("   |         / | \\");
            System.out.println("   |          / \\ ");
            System.out.println("___|___      /   \\");
            System.out.println();
        }
    }
}
